#!/usr/bin/env node
/**
 * build-sw.js — generates site/sw.js, the service worker that makes the hosted
 * app work with no internet.
 *
 * John uses the app at the pages.dev address, so "offline" has to mean that
 * address still working on a train. A service worker stores the app and its
 * content in the browser after the first visit; from then on it loads from
 * there. Same address, same localStorage, so his progress and the sync feature
 * are unaffected.
 *
 * The precache list is generated rather than hand-written, so it cannot drift
 * out of step with the files that actually exist.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SITE = path.join(ROOT, 'site');

// Everything needed to open the app and read every module offline. The heavy
// extras (past-paper PDFs, printable pages) are cached on first use instead, so
// the initial visit stays quick.
const PRECACHE = [
  // The host serves the app at an extensionless URL, and that is the address a
  // navigation actually requests, so it must be cached under that name too —
  // caching only app.html leaves the offline shell unreachable.
  'app',
  'app.html',
  'manifest.webmanifest',
  'assets/style.css',
  'app/app.css',
];

const walk = (dir, base) => fs.readdirSync(path.join(SITE, dir), { withFileTypes: true })
  .flatMap(e => e.isDirectory()
    ? walk(path.join(dir, e.name), base)
    : [path.join(dir, e.name).split(path.sep).join('/')]);

PRECACHE.push(...walk('app/js').filter(f => f.endsWith('.js')));
PRECACHE.push(...walk('content').filter(f => f.endsWith('.json')));

// version the cache off the content of everything precached, so a deploy that
// changes anything gets a fresh cache and a stale one is discarded
const hash = require('crypto').createHash('sha1');
for (const f of PRECACHE.slice().sort()) {
  // 'app' is a URL the host serves, not a file on disk (and it collides with the
  // app/ directory), so only real files contribute to the version hash
  const p = path.join(SITE, f);
  if (fs.existsSync(p) && fs.statSync(p).isFile()) hash.update(fs.readFileSync(p));
}
const VERSION = hash.digest('hex').slice(0, 12);

const sw = `/* generated by tools/build-sw.js — do not edit by hand */
const CACHE = 'app-${VERSION}';
const PRECACHE = ${JSON.stringify(PRECACHE, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // one at a time: a single 404 must not abandon the whole install
    await Promise.all(PRECACHE.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); } catch { /* skip */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && (key.startsWith('app-') || key.startsWith('physics-'))) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;                       // sync PUTs go straight out

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // never touch other hosts
  if (url.pathname.endsWith('/sync')) return;             // sync must always be live

  // A navigation with no connection still has to land on the app, whichever
  // form of the address was used. The host serves /app.html as a redirect to
  // /app, so the fallback is matched by absolute URL rather than by request.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try { return await fetch(req); }
      catch {
        const cache = await caches.open(CACHE);
        const shell = new URL('app.html', self.registration.scope).href;
        return (await cache.match(req, { ignoreSearch: true }))
          || (await cache.match(shell))
          || new Response('Offline, and the app has not been stored on this device yet.',
            { status: 503, headers: { 'content-type': 'text/plain' } });
      }
    })());
    return;
  }

  // Everything else: serve from store, refresh in the background, and cache
  // anything new that is fetched (so a PDF opened once stays available).
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    const live = fetch(req).then((res) => {
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    }).catch(() => null);
    return hit || (await live) || new Response('Not available offline yet.', { status: 504 });
  })());
});
`;

fs.writeFileSync(path.join(SITE, 'sw.js'), sw);
console.log(`wrote site/sw.js — cache app-${VERSION}, ${PRECACHE.length} files precached`);
